// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Television Network App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

"use client";
import React from "react";
import { IoIosArrowRoundForward } from "react-icons/io";
import { PiCarProfileLight } from "react-icons/pi";
import { VscListUnordered } from "react-icons/vsc";
import Link from "next/link";
import { AiFillSignal } from "react-icons/ai";
import { GiBurningTree } from "react-icons/gi";
import { FaCircle } from "react-icons/fa";
import { IoNotifications } from "react-icons/io5";
import { DashboardTwo } from "./dashboard/page"

const sideBar = [
  {
    Arrow: IoIosArrowRoundForward,
    Icon: PiCarProfileLight,
    name: "channel",
    slug: "channel",
    href: "/admintwo/channel",
  },
  {
    Arrow: IoIosArrowRoundForward,
    Icon: VscListUnordered,
    name: "Program",
    slug: "program",
    href: "/admintwo/program",
  },
];

const page = ({ children }) => {
  return (
    <div className="">
      <div className="flex w-screen  bg-gray-100 shadow-sm">
        <div className="mx-5 ">
          <GiBurningTree size={60} />
        </div>
        <div className="mx-16 my-2">
          <h1 className="text-xl">T- Movie</h1>
        </div>

        <div className=" flex w-full bg-slate-900">
          <div className="mx-10 flex justify-start">
            <h2 className="text-xl mr-100 text-white mt-4">Dashboard</h2>
          </div>
          <div className="flex justify-between  mt-4 ml-100 ">
            <small className="">
              <IoNotifications size={30} style={{ fill: "white" }} />
            </small>
            <small className="">
              <FaCircle size={30} style={{ fill: "white" }} />
            </small>
          </div>
        </div>
      </div>

      <div className="flex h-screen  bg-gray-100 ">
        <div className="  w-1/4  flex justify-center">
          <div className="">
            <div className=" w-full h-screen ">
              <Link href="/admintwo/dashboardtwo">
                <div className="  py-3 px-16    hover:bg-slate-800 flex my-5">
                  <div>
                    {" "}
                    <AiFillSignal className="w-7 h-7 mr-4 hover:text-white" />{" "}
                  </div>
                  <div className="hover:text-white">Dashboard</div>
                </div>
              </Link>

              {sideBar.map(({ Icon, name, slug, href }, ind) => (
                <Link key={ind} href={`${href ? href : ""}`}>
                  <div className=" items-center   py-3 px-20 hover:shadow-lg  hover:bg-slate-900 flex my-5">
                    <div>
                      {" "}
                      <Icon className="w-7 h-7 mr-3  hover:text-white" />{" "}
                    </div>
                    <div className="hover:text-white">{name}</div>
                  </div>
                </Link>
              ))}
            </div>
          </div>
        </div>
        <div className="shadow-lg w-full h-screen scrollbar scrollbar-thumb-sky-700 scrollbar-track-sky-300  overflow-y-scroll">
          {/* <DashboardTwo/> */}
          {children}
        </div>
      </div>
    </div>
  );
};

export default page;

// https://www.youtube.com/watch?v=N51ik3kUqxE
