import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Television Network App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}


// import { Inter } from "next/font/google";
// import NavBar from "../components/Nav/NavBar";
// // import Footer from "../components/Footer/Footer";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Television Network App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head>
//         <title>{metadata.title}</title>
//         <meta name="description" content={metadata.description} />
//       </head>
//       <body className={inter.className}>
//         <NavBar />
//         <main>{children}</main>
//         {/* <Footer /> */}
//       </body>
//     </html>
//   );
// }
